### ISSUE TITLE
Document not active when combine with react-hls-player

### ISSUE THREAD

**Issue by nmhung1234** [napthedev/react-tuby#8]
This is my code follow to readme.md
![image](https://user-images.githubusercontent.com/72334885/174217067-3b22a7df-d5b9-43b2-bf5a-aa7ec90f2fa3.png)
and this is my bug: 
![image](https://user-images.githubusercontent.com/72334885/174217271-f2beb3d5-3c3d-4d5e-9a3a-3fde563d56c8.png)

**Comment by napthedev** [comment]
I have updated the package to fix the problem, please install the latest version of the package.

**Comment by nmhung1234** [comment]
> I have updated the package to fix the problem, please install the latest version of the package.

Ya. The best player i found!!!
